### ISSUE TITLE
Remove ZIO NIO Dependency From ZMX Client

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#100]
The ZMX client, located in the `ZMXClient.scala` file, currently uses `zio.nio` in its implementation. We want ZIO ZMX to have no dependencies other than ZIO itself so it is as easy as possible for users to add to their application.

This ticket is to refactor the ZMX client to implement the functionality directly in terms of non-blocking methods from `java.nio`. A completed ticket will also have tests to verify that this functionality is working correctly.

**Comment by ahoy-jon** [comment]
I started looking at this one, so far, it looks doable.
