### ISSUE TITLE
Remove ZIO NIO Dependency From ZMX Server

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#101]
The ZMX server, located in the ZMXServer.scala file, currently uses `zio.nio` in its implementation. We want ZIO ZMX to have no dependencies other than ZIO itself so it is as easy as possible for users to add to their application.

This ticket is to refactor the ZMX server to implement the functionality directly in terms of non-blocking methods from `java.nio`. A completed ticket will also have tests to verify that this functionality is working correctly.

**Comment by alesavin** [comment]
I'll get this one for hackaton

**Comment by alesavin** [comment]
Sorry, have no enough time to finish issue during hackaton, but I will continue work here. I like project in general!

**Comment by alesavin** [comment]
#159
