### ISSUE TITLE
Remove ZIO NIO Dependency From UDP Client

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#102]
The UDP client, located in the `UDPClient.scala` file, currently uses `zio.nio` in its implementation. We want ZIO ZMX to have no dependencies other than ZIO itself so it is as easy as possible for users to add to their application.

This ticket is to refactor the UDP client to implement the functionality directly in terms of non-blocking methods from `java.nio`. A completed ticket will also have tests to verify that this functionality is working correctly.

**Comment by benetis** [comment]
I would like to work on this one.

**Comment by ahoy-jon** [comment]
@benetis @alesavin if you want to work together on it with #100 #101, don't hesitate to ping on discord. (I am on #100)

**Comment by benetis** [comment]
@ahoy-jon sure
