### ISSUE TITLE
Create Prometheus Data Model

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#107]
We want ZIO ZMX to support Promtheus as well as statd. We currently support a version of this today, see the `PrometheusSpec.scala` file in the `test` folder, but it relies on a dependency on the Prometheus client which we do not want to have. Therefore, we need to do our own implementation of the Prometheus protocol.

The first step to do this is to create a data model for the objects within the Prometheus data model, for example the `Counter`, `Histogram`, and `CollectorRegistry`. At this point this would be a pure data model that would describe the information we would need to interact with Prometheus but would not contain any of the actual logic for converting this data into the format expected by Prometheus.

**Comment by atooni** [comment]
Apart from working on ticket https://github.com/zio/zio/issues/4384 I would like to give this a go in the hackathon.

**Comment by toxicafunk** [comment]
The model needs to able to output the [write004 TextFormat](https://github.com/prometheus/client_java/blob/master/simpleclient_common/src/main/java/io/prometheus/client/exporter/common/TextFormat.java) which is what the Prometheus Server interprets in order to create its graphs.

**Comment by adamgfraser** [comment]
@atooni Great!

**Comment by atooni** [comment]
Specification of the text format : https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by atooni** [comment]
I propose to close this as the PR has been merged
