### ISSUE TITLE
Create Prometheus Server

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#109]
Building on #107 and #108 this ticket is to create an actual implementation of a ZMX server that interacts with Prometheus using our own data model and encoder.

A completed ticket would implement the same functionality demonstrated in in the `PromthetheusSpec.scala` file but would not have any dependency on a third party Prometheus client. Our own implementation can be put in the `zio.zmx.promthetheus` package with a `live` method that constructs the server.

**Comment by atooni** [comment]
I am working on that now - trying to get a simple roundtrip to Prometheus
