### ISSUE TITLE
Simplify Service Implementations

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#110]
ZIO ZMX contains several implementations of services in the environment. While this pattern is very useful, it is helpful primarily when we want to support alternative implementations of a service. There are several cases where we currently have functionality implemented as services that will never have more than one implementation. In these cases code can be simplified by moving the functionality to normal methods on an object.

This ticket is to do the following:

- [ ] Delete the `FiberDumpProvider` service in the `fibers` package and inline its functionality into the `Diagnostics` service in the `zio.zmx` package object since it is not used anywhere else. Once we do this we can delete the `fibers` package object entirely.
- [x] Make the functionality in the `parser` package a set of static methods since we only expect to ever have one RESP Parser. I would also rename this to `RESPParser` for clarity.

**Comment by lkff** [comment]
The second part of this ticket is something that I have in mind in #125 while working on #9 and #76.

**Comment by adamgfraser** [comment]
@lkff Sounds good. Let's scope this ticket to just the first part then to avoid duplication of work.

**Comment by KadekM** [comment]
@adamgfraser I'll take the first part then

**Comment by lkff** [comment]
Second part of this ticket can be considered done after #140 gets merged 👍

**Comment by KadekM** [comment]
@adamgfraser is this done or should I do anything?

**Comment by adamgfraser** [comment]
@KadekM We can close this.
