### ISSUE TITLE
Delete ZMXServer Trait

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#113]
The ZMXServer trait currently only has a single method, `close` that closes the channel. We can delete this trait and have the `ZMXServer.make` operator return either a `ZManaged` or a `ZLayer` that builds in the necessary finalization logic.

**Comment by KadekM** [comment]
I'd like to do this one for hackaton

**Comment by adamgfraser** [comment]
@KadekM Great!

**Comment by KadekM** [comment]
@adamgfraser i think we can close this one
