### ISSUE TITLE
Separate Definition And Interpretation of Statsd Data Model

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#114]
A data model for StatsD exists in the `MetricsDataModel` folder. Right now this to a certain extent mixes the definition of a data model (e.g. `ServiceCheckStatus.Ok`) with the interpretation of that model `val value: Int = 0`.

We can clean this up by implementing a separate method that "interprets" an object and pattern matching:

```scala
def encode(status: ServiceCheckStatus): Int =
  ???
```

It may make sense to have all the types in the data model inherit from one common super type so we can encode any of them.

**Comment by asjad02** [comment]
@adamgfraser 
picking this up
