### ISSUE TITLE
Explore MetricAttributes Data Type

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#116]
We have several methods on the `Metrics` service that take a large number of parameters, including `serviceCheck` and `event`. This can create a less than ideal API for the user because it can require specifying parameters that are not needed or lead to confusing the order of parameters since several have the same type (e.g. `Option[String]`).

An alternative is to have a `MetricAttributes` data type. Then each of these methods could just accept a `Set[MetricAttributes]` instead of all of these individual arguments and the library would internally traverse those attributes and construct the metric accordingly.

This ticket would involve creating the `MetricAttributes` data type, including smart constructors that make it easy for users to create the common types of metric attributes that are already represented in these signatures, and functionality to interpret the attributes back to the required parameters when needed, demonstrating that the same functionality that works today works with this new encoding.

**Comment by lbdlbdlbdl** [comment]
I take this ticket :)

**Comment by atooni** [comment]
I believe this will be rolled up in the work unifying the API#s in #155
