### ISSUE TITLE
Explore Simplifying Signature of Listen Method

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#118]
The signature of the `listen` method on the `Metrics` service is currently:

```scala
override def listen(f: List[Metric[_]] => IO[Exception, List[Long]]): ZIO[Clock, Throwable, Fiber.Runtime[Throwable, Nothing]]
```

It is very unclear from this signature what the `List[Long]` is supposed to represent. We should consider whether we can can simplify `f` to `List[Metric[_]] => IO[Exception, Unit]), basically, "you give me a function that takes a list of metrics and does some side effect with them, I will give you back an effect that listens for those forever".

We should also look at whether we can simplify the result type to `IO[Throwable, Nothing]`. This would indicate that the effect will never succeed because it represents a server that will just keep running forever. The caller of the method could then fork it to get the fiber that is currently returned but we separate concerns a little more.

Finally, we should look at how this method can actually fail and if the error types are as specific as possible.

**Comment by n-s-kozlovskii** [comment]
I'd like to take this issue if it is a good choice as fist time contribution

**Comment by n-s-kozlovskii** [comment]
@adamgfraser  After replacing ListLong] with Unit I struggle to rewrite tests, as we check how much data we've sent with list.sum and list.length. If there is Unit, we have nothing to assert on. Do we need to keep tests, that depend on fact, that f return List[Long]? What other possible use cases could be found, that require f to return List[Long]?

**Comment by aartigao** [comment]
I think that even with `f: List[Metric[_]] => IO[Exception, Unit]`you can make assertions about data sent.

Something like this should work:

```
for {
  accum <- Ref.make(Accumulator)
  _ <- listen(m => IO(modify accum here).unit)
  _ <- calls to service that triggers your test function
} yield assert(accum)(whatever)
```

Let me know if you have any problems ☝🏽
