### ISSUE TITLE
Use Chunk

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#119]
We have a variety of cases where we are using `List` for a collection. Unless there is a specific reason we want linear access we should generally be using ZIO's `Chunk` data type as it provides good performance for a range of operations that require linear or random access and has fast append and prepend.

This ticket is to go through ZIO ZMX and replaces `List` with `Chunk` wherever possible.

**Comment by shankarshastri** [comment]
@adamgfraser , I can pick this and spend on the same for the hackathon.
