### ISSUE TITLE
Delete listenUnsafe Method

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#120]
ZIO ZMX supports a concept of an "unsafe" service to allow users to record metrics with less overhead in certain cases. This makes sense in general but the `listenUnsafe` method is doing things that are directly in the wheelhouse of ZIO and are much less safe without ZIO. We should delete this method and implement it in terms of the existing `listen` method.

**Comment by aartigao** [comment]
I can work on this one 🙂

**Comment by adamgfraser** [comment]
@aartigao Awesome!
