### ISSUE TITLE
Check For Spin Loops

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#121]
We should review the code to see if we have any places where we are busy polling for a variable to be true. In particular, it looks like in the `collect` method in the `zio.zmx` package object we are repeatedly polling the queue. We should see if there is another way to refactor this code to avoid this and review the rest of the code to see if there are any other cases like this.

**Comment by vigoo** [comment]
working on this

**Comment by adamgfraser** [comment]
Awesome!
