### ISSUE TITLE
General Cleanup

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#122]
This ticket is for general cleanup and polishing of ZIO ZMX code base, focusing on the following:

- [ ] Remove debug `println` statements
- [ ] Case classes should be final
- [ ] Method names should be lower case
- [ ] Methods that aren't side effecting with no arguments should not have `()` after them
- [ ] Methods that don't have arguments should generally be `val` rather than `def`

**Comment by shankarshastri** [comment]
@adamgfraser , I can try to work on this one.

**Comment by adamgfraser** [comment]
@shankarshastri Great!

**Comment by angelicarao** [comment]
@shankarshastri If you won't be working on this one, let me know, I can pick it up as well :)

**Comment by shankarshastri** [comment]
@angelicarao , Thanks, but I will be working on it :)
