### ISSUE TITLE
Use `Set` instead of `SortedSet`

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#123]
Currently in the `ZMXSupervisor` and related data types we use a `SortedSet` of fibers. I don't think there is any reason the set needs to be sorted. An ordinary set of fibers backed by a `HashSet` would have better performance.

**Comment by shankarshastri** [comment]
@adamgfraser , I can work on this for the zio-hackathon.

**Comment by adamgfraser** [comment]
@shankarshastri You're all over it!
