### ISSUE TITLE
Revisit `ExecutionMetrics` representation in terms of RESP

### ISSUE THREAD

**Issue by lkff** [zio/zio-zmx#142]
In recently merged #140 I've added this `TODO` comment:

```scala
    case ZMXProtocol.Response.Success(data) =>
      data match {
        case executionMetrics: ZMXProtocol.Data.ExecutionMetrics =>
          // TODO: Format of `ExecutionMetrics` serialized could be discussed and revisited.
          Resp.BulkString(executionMetrics.toString).serialize
```

In that PR I've actually kept the previous format but I think we can improve it with use of other RESP
types (especially with recent proper implementation of RESP added :wink:).

The metrics themselves have this form:
```scala
abstract class ExecutionMetrics {
  def concurrency: Int
  def capacity: Int
  def size: Int
  def enqueuedCount: Long
  def dequeuedCount: Long
  def workersCount: Int
}
```

Right now they are sent as one big Bulk String:
```
$86\r\n
concurrency:1\r\n
capacity:2\r\n
size:3\r\n
enqueued_count:4\r\n
dequeued_count:5\r\n
workers_count:6\r\n
```
This after parsing from RESP format gives a string of `"concurrency:1\r\ncapacity:2\r\nsize:3\r\nenqueued_count:4\r\ndequeued_count:5\r\nworkers_count:6"` that client has to parse again.

Definitely `Array` type could be used. While RESP does not support key-value structures,
I think instead of encoding them as `key:value` we could use `Array`s again.
Then these values, since they are `Int`/`Long`, could be represented as RESP `Integer`s.

So I'd propose something along:
```scala
Array(
  Array(
    SimpleString("concurrency"),
    Integer(1)
  ),
  Array(
    SimpleString("capacity"),
    Integer(2)
  ),
  [...]
)
```

I'm leaving this open for discussion.
It's more of question how much of RESP types do we want to use because API clients will have to support it.

But if we're already using decent part of it, then why not just use its full power?
I think that using proper RESP types would make more sense than asking clients to parse the result again, now from of our `key:value`/`CRLF` not-standard format 😉 

Pinging @jczuchnowski since you've been working on that part.

**Comment by jczuchnowski** [comment]
I based this design o Redis protocol for [CLUSTER INFO](https://redis.io/commands/cluster-info) and [INFO](https://redis.io/commands/info) commands.So it's not like we're not usig the power of RESP, as RESP creators are using it like that ;).
That said, the reason for Redis to do it like this might be this comment for `INFO`:
```
Please note depending on the version of Redis some of the fields have been added or removed. A robust client application should therefore parse the result of this command by skipping unknown properties, and gracefully handle missing fields.
```
I suppose it could be argued that Bulk String allows for a more "dynamic" parsing of the structure. In any case I don't think we need it for the execution metrics.

Now the one thing that bothers me is how to put into this feature execution metrics from both non-blocking and blocking executors. Bulk String would solve it with sections separated by comments (like in Redis `INFO`):
```
# Clients
connected_clients:2
client_recent_max_input_buffer:8
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:199970040
used_memory_human:190.71M
used_memory_rss:211603456
used_memory_rss_human:201.80M
...
```
So how do we do it nicely with Arrays?

**Comment by jczuchnowski** [comment]
Actually I'm curious if there are examples in Redis protocol of using Arrays for key/value lists.

**Comment by lkff** [comment]
Yeah, so RESP's `Bulk String`s are basically for sending any data.
But it's basically using RESP to send custom _protocol_ that client has to parse - that was my point.
There are few possible approaches for key-value collections, for example we could have the execution metrics represented as:
```scala
Array(
  Array(
    SimpleString("defaultExecutor"),
    Array(
      Array(SimpleString("concurrency"), Integer(101)),
      Array(SimpleString("capacity"), Integer(102)),
      Array(SimpleString("size"), Integer(103)),
      Array(SimpleString("enqueuedCount"), Integer(104)),
      Array(SimpleString("dequeuedCount"), Integer(105)),
      Array(SimpleString("workersCount"), Integer(106))
    )
  ),
  Array(
    SimpleString("blockingExecutor"),
    Array(
      Array(SimpleString("concurrency"), Integer(201)),
      Array(SimpleString("capacity"), Integer(202)),
      Array(SimpleString("size"), Integer(203)),
      Array(SimpleString("enqueuedCount"), Integer(204)),
      Array(SimpleString("dequeuedCount"), Integer(205)),
      Array(SimpleString("workersCount"), Integer(206))
    )
  )
)
```

Well, you see where it's going 😄
It's _a bit_ verbose, but that's the full form that requires minimum of assumptions for client.
Hence the discussion, how much of RESP you want to use for that.

**Comment by adamgfraser** [comment]
Closing as this is being handled at the ZIO core level at this point.
