### ISSUE TITLE
Delete All Code Not Related To Metric Client Implementations

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-zmx#307]
With ZIO 2.0 the vision for this library has sharpened to providing implementations of metrics clients that can book into the metrics functionality provided by ZIO Core. All code not necessary for the implementation of metrics clients (e.g. definition of metrics and metric aspects, concurrent state) should be deleted.

**Comment by atooni** [comment]
I think the diagnostics code is moving to the core as well, so that can be deleted as well.
