### ISSUE TITLE
Server fails when handling a bad RESP request

### ISSUE THREAD

**Issue by jczuchnowski** [zio/zio-zmx#76]
When issued a bad bulk string command the ZMX server fails and doesn't respond to subsequent requests.

Example bad request (wrong char number):
```
echo -ne '*1\r\n$3\r\ndump\r\n' | nc localhost 1111
```
should be:
```
echo -ne '*1\r\n$4\r\ndump\r\n' | nc localhost 1111
```

**Comment by lkff** [comment]
I would solve this issue after #125 gets merged.
